/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BelajarRouteImport } from './routes/belajar'
import { Route as BermainRouteImport } from './routes/bermain'
import { Route as CaraBermainRouteImport } from './routes/cara-bermain'
import { Route as KartuRouteImport } from './routes/kartu'
import { Route as OnlineRouteImport } from './routes/online'
import { Route as RefleksiRouteImport } from './routes/refleksi'
import { Route as TentangRouteImport } from './routes/tentang'
import { Route as ApiTtsRouteImport } from './routes/api/tts'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BelajarRoute = BelajarRouteImport.update({
  id: '/belajar',
  path: '/belajar',
  getParentRoute: () => rootRouteImport,
} as any)
const BermainRoute = BermainRouteImport.update({
  id: '/bermain',
  path: '/bermain',
  getParentRoute: () => rootRouteImport,
} as any)
const CaraBermainRoute = CaraBermainRouteImport.update({
  id: '/cara-bermain',
  path: '/cara-bermain',
  getParentRoute: () => rootRouteImport,
} as any)
const KartuRoute = KartuRouteImport.update({
  id: '/kartu',
  path: '/kartu',
  getParentRoute: () => rootRouteImport,
} as any)
const OnlineRoute = OnlineRouteImport.update({
  id: '/online',
  path: '/online',
  getParentRoute: () => rootRouteImport,
} as any)
const RefleksiRoute = RefleksiRouteImport.update({
  id: '/refleksi',
  path: '/refleksi',
  getParentRoute: () => rootRouteImport,
} as any)
const TentangRoute = TentangRouteImport.update({
  id: '/tentang',
  path: '/tentang',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/belajar': typeof BelajarRoute
  '/bermain': typeof BermainRoute
  '/cara-bermain': typeof CaraBermainRoute
  '/kartu': typeof KartuRoute
  '/online': typeof OnlineRoute
  '/refleksi': typeof RefleksiRoute
  '/tentang': typeof TentangRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/belajar': typeof BelajarRoute
  '/bermain': typeof BermainRoute
  '/cara-bermain': typeof CaraBermainRoute
  '/kartu': typeof KartuRoute
  '/online': typeof OnlineRoute
  '/refleksi': typeof RefleksiRoute
  '/tentang': typeof TentangRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/belajar': typeof BelajarRoute
  '/bermain': typeof BermainRoute
  '/cara-bermain': typeof CaraBermainRoute
  '/kartu': typeof KartuRoute
  '/online': typeof OnlineRoute
  '/refleksi': typeof RefleksiRoute
  '/tentang': typeof TentangRoute
  '/api/tts': typeof ApiTtsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/belajar'
    | '/bermain'
    | '/cara-bermain'
    | '/kartu'
    | '/online'
    | '/refleksi'
    | '/tentang'
    | '/api/tts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/belajar'
    | '/bermain'
    | '/cara-bermain'
    | '/kartu'
    | '/online'
    | '/refleksi'
    | '/tentang'
    | '/api/tts'
  id:
    | '__root__'
    | '/'
    | '/belajar'
    | '/bermain'
    | '/cara-bermain'
    | '/kartu'
    | '/online'
    | '/refleksi'
    | '/tentang'
    | '/api/tts'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BelajarRoute: typeof BelajarRoute
  BermainRoute: typeof BermainRoute
  CaraBermainRoute: typeof CaraBermainRoute
  KartuRoute: typeof KartuRoute
  OnlineRoute: typeof OnlineRoute
  RefleksiRoute: typeof RefleksiRoute
  TentangRoute: typeof TentangRoute
  ApiTtsRoute: typeof ApiTtsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/belajar': {
      id: '/belajar'
      path: '/belajar'
      fullPath: '/belajar'
      preLoaderRoute: typeof BelajarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bermain': {
      id: '/bermain'
      path: '/bermain'
      fullPath: '/bermain'
      preLoaderRoute: typeof BermainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cara-bermain': {
      id: '/cara-bermain'
      path: '/cara-bermain'
      fullPath: '/cara-bermain'
      preLoaderRoute: typeof CaraBermainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartu': {
      id: '/kartu'
      path: '/kartu'
      fullPath: '/kartu'
      preLoaderRoute: typeof KartuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/online': {
      id: '/online'
      path: '/online'
      fullPath: '/online'
      preLoaderRoute: typeof OnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refleksi': {
      id: '/refleksi'
      path: '/refleksi'
      fullPath: '/refleksi'
      preLoaderRoute: typeof RefleksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tentang': {
      id: '/tentang'
      path: '/tentang'
      fullPath: '/tentang'
      preLoaderRoute: typeof TentangRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BelajarRoute: BelajarRoute,
  BermainRoute: BermainRoute,
  CaraBermainRoute: CaraBermainRoute,
  KartuRoute: KartuRoute,
  OnlineRoute: OnlineRoute,
  RefleksiRoute: RefleksiRoute,
  TentangRoute: TentangRoute,
  ApiTtsRoute: ApiTtsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
